import { Lightbulb, Flame, Droplets, BrickWall, Brush, Hammer, Sprout, Wrench, Key, Truck, Sparkles, House, Megaphone, SprayCan, Bike, Car } from 'lucide-react';

export const PROFESSIONS = [
  { name: 'Electricista', icon: Lightbulb, category: 'Hogar y Construcción' },
  { name: 'Gasista', icon: Flame, category: 'Hogar y Construcción' },
  { name: 'Plomero', icon: Droplets, category: 'Hogar y Construcción' },
  { name: 'Albañil', icon: BrickWall, category: 'Hogar y Construcción' },
  { name: 'Pintor', icon: Brush, category: 'Hogar y Construcción' },
  { name: 'Carpintero', icon: Hammer, category: 'Hogar y Construcción' },
  { name: 'Jardinero', icon: Sprout, category: 'Hogar y Construcción' },
  { name: 'Techista', icon: House, category: 'Hogar y Construcción' },
  { name: 'Cerrajero', icon: Key, category: 'Servicios Generales' },
  { name: 'Flete', icon: Truck, category: 'Servicios Generales' },
  { name: 'Limpieza', icon: Sparkles, category: 'Servicios Generales' },
  { name: 'Mecánico', icon: Wrench, category: 'Automotor' },
  { name: 'Pintor Autos', icon: SprayCan, category: 'Automotor' },
  { name: 'Mecánico Motos', icon: Bike, category: 'Automotor' },
  { name: 'Mecánico Autos', icon: Car, category: 'Automotor' },
  { name: 'Mecánico Camiones', icon: Truck, category: 'Automotor' },
  { name: 'Community Manager', icon: Megaphone, category: 'Digital y Diseño' },
];

export const ZONAS = [
  'Centro', 
  'Macrocentro',
  'Universitario', 
  'Villa Mitre', 
  'Patagonia', 
  'Noroeste',
  'Los Almendros',
  'Norte', 
  'Bella Vista', 
  'Palihue', 
  'San Andrés', 
  'Tiro Federal', 
  'Ingeniero White',
  'Aldea Romana',
  'Villa Harding Green',
  'Villa Rosas',
  'Las Villas',
  'Pacífico',
  'La Falda',
  'Napostá',
  'Pedro Pico',
  'General Daniel Cerri',
  'Cabildo'
];
